### ISSUE TITLE
OperationalError: no such table: main

### ISSUE THREAD

**Issue by siddhantBhatt989** [Ak1957/Jio-Magazine-Downloader#7]
downloads images but then when i click at any mag it stucks  and give the following error 

Datadata = query_handler.query("web\\database\\"+database,"main", None)File "E:\PDFNetPython3\Jio-Magazine-Downloader-master\JIO Mags\query_handler.py", line 17, in querycrsr.execute(sql_statement)sqlite3.OperationalError: no such table: main

**Comment by siddhantBhatt989** [comment]
```
Traceback (most recent call last):
  File "C:\Users\Yash\AppData\Roaming\Python\Python37\site-packages\eel\__init__.py", line 281, in _process_message
    return_val = _exposed_functions[message['name']](*message['args'])
  File "E:\PDFNetPython3\Jio-Magazine-Downloader-master\JIO Mags\main_script.py", line 17, in getImagebyID
    return fetchIssueData.getPageData(magid)
  File "E:\PDFNetPython3\Jio-Magazine-Downloader-master\JIO Mags\fetchIssueData.py", line 62, in getPageData
    data = query_handler.query("web\\database\\"+database,"main", None)
  File "E:\PDFNetPython3\Jio-Magazine-Downloader-master\JIO Mags\query_handler.py", line 17, in query
    crsr.execute(sql_statement)
sqlite3.OperationalError: no such table: main
```
